/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportingRouteImport } from './routes/reporting'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileSetupRouteImport } from './routes/profile-setup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as AuthReadyRouteImport } from './routes/auth-ready'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsIndexRouteImport } from './routes/tools/index'
import { Route as MigrateIndexRouteImport } from './routes/migrate/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ToolsWeightLossCalculatorRouteImport } from './routes/tools/weight-loss-calculator'
import { Route as ToolsTdeeCalculatorRouteImport } from './routes/tools/tdee-calculator'
import { Route as ToolsProteinCalculatorRouteImport } from './routes/tools/protein-calculator'
import { Route as ToolsMacroCalculatorRouteImport } from './routes/tools/macro-calculator'
import { Route as ToolsBmrCalculatorRouteImport } from './routes/tools/bmr-calculator'
import { Route as MigrateSlugRouteImport } from './routes/migrate/$slug'
import { Route as CompareSlugRouteImport } from './routes/compare/$slug'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportingRoute = ReportingRouteImport.update({
  id: '/reporting',
  path: '/reporting',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSetupRoute = ProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthReadyRoute = AuthReadyRouteImport.update({
  id: '/auth-ready',
  path: '/auth-ready',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateIndexRoute = MigrateIndexRouteImport.update({
  id: '/migrate/',
  path: '/migrate/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWeightLossCalculatorRoute =
  ToolsWeightLossCalculatorRouteImport.update({
    id: '/tools/weight-loss-calculator',
    path: '/tools/weight-loss-calculator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsTdeeCalculatorRoute = ToolsTdeeCalculatorRouteImport.update({
  id: '/tools/tdee-calculator',
  path: '/tools/tdee-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsProteinCalculatorRoute = ToolsProteinCalculatorRouteImport.update({
  id: '/tools/protein-calculator',
  path: '/tools/protein-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMacroCalculatorRoute = ToolsMacroCalculatorRouteImport.update({
  id: '/tools/macro-calculator',
  path: '/tools/macro-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBmrCalculatorRoute = ToolsBmrCalculatorRouteImport.update({
  id: '/tools/bmr-calculator',
  path: '/tools/bmr-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateSlugRoute = MigrateSlugRouteImport.update({
  id: '/migrate/$slug',
  path: '/migrate/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareSlugRoute = CompareSlugRouteImport.update({
  id: '/compare/$slug',
  path: '/compare/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth-ready': typeof AuthReadyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reporting': typeof ReportingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/migrate/$slug': typeof MigrateSlugRoute
  '/tools/bmr-calculator': typeof ToolsBmrCalculatorRoute
  '/tools/macro-calculator': typeof ToolsMacroCalculatorRoute
  '/tools/protein-calculator': typeof ToolsProteinCalculatorRoute
  '/tools/tdee-calculator': typeof ToolsTdeeCalculatorRoute
  '/tools/weight-loss-calculator': typeof ToolsWeightLossCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/migrate/': typeof MigrateIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth-ready': typeof AuthReadyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reporting': typeof ReportingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/migrate/$slug': typeof MigrateSlugRoute
  '/tools/bmr-calculator': typeof ToolsBmrCalculatorRoute
  '/tools/macro-calculator': typeof ToolsMacroCalculatorRoute
  '/tools/protein-calculator': typeof ToolsProteinCalculatorRoute
  '/tools/tdee-calculator': typeof ToolsTdeeCalculatorRoute
  '/tools/weight-loss-calculator': typeof ToolsWeightLossCalculatorRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/migrate': typeof MigrateIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth-ready': typeof AuthReadyRoute
  '/delete-account': typeof DeleteAccountRoute
  '/goals': typeof GoalsRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/profile-setup': typeof ProfileSetupRoute
  '/register': typeof RegisterRoute
  '/reporting': typeof ReportingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/compare/$slug': typeof CompareSlugRoute
  '/migrate/$slug': typeof MigrateSlugRoute
  '/tools/bmr-calculator': typeof ToolsBmrCalculatorRoute
  '/tools/macro-calculator': typeof ToolsMacroCalculatorRoute
  '/tools/protein-calculator': typeof ToolsProteinCalculatorRoute
  '/tools/tdee-calculator': typeof ToolsTdeeCalculatorRoute
  '/tools/weight-loss-calculator': typeof ToolsWeightLossCalculatorRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/migrate/': typeof MigrateIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth-ready'
    | '/delete-account'
    | '/goals'
    | '/home'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile-setup'
    | '/register'
    | '/reporting'
    | '/reset-password'
    | '/settings'
    | '/sso-callback'
    | '/terms'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/migrate/$slug'
    | '/tools/bmr-calculator'
    | '/tools/macro-calculator'
    | '/tools/protein-calculator'
    | '/tools/tdee-calculator'
    | '/tools/weight-loss-calculator'
    | '/blog/'
    | '/compare/'
    | '/migrate/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth-ready'
    | '/delete-account'
    | '/goals'
    | '/home'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile-setup'
    | '/register'
    | '/reporting'
    | '/reset-password'
    | '/settings'
    | '/sso-callback'
    | '/terms'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/migrate/$slug'
    | '/tools/bmr-calculator'
    | '/tools/macro-calculator'
    | '/tools/protein-calculator'
    | '/tools/tdee-calculator'
    | '/tools/weight-loss-calculator'
    | '/blog'
    | '/compare'
    | '/migrate'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/auth-ready'
    | '/delete-account'
    | '/goals'
    | '/home'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/profile-setup'
    | '/register'
    | '/reporting'
    | '/reset-password'
    | '/settings'
    | '/sso-callback'
    | '/terms'
    | '/blog/$slug'
    | '/compare/$slug'
    | '/migrate/$slug'
    | '/tools/bmr-calculator'
    | '/tools/macro-calculator'
    | '/tools/protein-calculator'
    | '/tools/tdee-calculator'
    | '/tools/weight-loss-calculator'
    | '/blog/'
    | '/compare/'
    | '/migrate/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthReadyRoute: typeof AuthReadyRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  GoalsRoute: typeof GoalsRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileSetupRoute: typeof ProfileSetupRoute
  RegisterRoute: typeof RegisterRoute
  ReportingRoute: typeof ReportingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  TermsRoute: typeof TermsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CompareSlugRoute: typeof CompareSlugRoute
  MigrateSlugRoute: typeof MigrateSlugRoute
  ToolsBmrCalculatorRoute: typeof ToolsBmrCalculatorRoute
  ToolsMacroCalculatorRoute: typeof ToolsMacroCalculatorRoute
  ToolsProteinCalculatorRoute: typeof ToolsProteinCalculatorRoute
  ToolsTdeeCalculatorRoute: typeof ToolsTdeeCalculatorRoute
  ToolsWeightLossCalculatorRoute: typeof ToolsWeightLossCalculatorRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CompareIndexRoute: typeof CompareIndexRoute
  MigrateIndexRoute: typeof MigrateIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reporting': {
      id: '/reporting'
      path: '/reporting'
      fullPath: '/reporting'
      preLoaderRoute: typeof ReportingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-setup': {
      id: '/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof ProfileSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-ready': {
      id: '/auth-ready'
      path: '/auth-ready'
      fullPath: '/auth-ready'
      preLoaderRoute: typeof AuthReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate/': {
      id: '/migrate/'
      path: '/migrate'
      fullPath: '/migrate/'
      preLoaderRoute: typeof MigrateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/': {
      id: '/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/weight-loss-calculator': {
      id: '/tools/weight-loss-calculator'
      path: '/tools/weight-loss-calculator'
      fullPath: '/tools/weight-loss-calculator'
      preLoaderRoute: typeof ToolsWeightLossCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tdee-calculator': {
      id: '/tools/tdee-calculator'
      path: '/tools/tdee-calculator'
      fullPath: '/tools/tdee-calculator'
      preLoaderRoute: typeof ToolsTdeeCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/protein-calculator': {
      id: '/tools/protein-calculator'
      path: '/tools/protein-calculator'
      fullPath: '/tools/protein-calculator'
      preLoaderRoute: typeof ToolsProteinCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/macro-calculator': {
      id: '/tools/macro-calculator'
      path: '/tools/macro-calculator'
      fullPath: '/tools/macro-calculator'
      preLoaderRoute: typeof ToolsMacroCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/bmr-calculator': {
      id: '/tools/bmr-calculator'
      path: '/tools/bmr-calculator'
      fullPath: '/tools/bmr-calculator'
      preLoaderRoute: typeof ToolsBmrCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate/$slug': {
      id: '/migrate/$slug'
      path: '/migrate/$slug'
      fullPath: '/migrate/$slug'
      preLoaderRoute: typeof MigrateSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/$slug': {
      id: '/compare/$slug'
      path: '/compare/$slug'
      fullPath: '/compare/$slug'
      preLoaderRoute: typeof CompareSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthReadyRoute: AuthReadyRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  GoalsRoute: GoalsRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileSetupRoute: ProfileSetupRoute,
  RegisterRoute: RegisterRoute,
  ReportingRoute: ReportingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  TermsRoute: TermsRoute,
  BlogSlugRoute: BlogSlugRoute,
  CompareSlugRoute: CompareSlugRoute,
  MigrateSlugRoute: MigrateSlugRoute,
  ToolsBmrCalculatorRoute: ToolsBmrCalculatorRoute,
  ToolsMacroCalculatorRoute: ToolsMacroCalculatorRoute,
  ToolsProteinCalculatorRoute: ToolsProteinCalculatorRoute,
  ToolsTdeeCalculatorRoute: ToolsTdeeCalculatorRoute,
  ToolsWeightLossCalculatorRoute: ToolsWeightLossCalculatorRoute,
  BlogIndexRoute: BlogIndexRoute,
  CompareIndexRoute: CompareIndexRoute,
  MigrateIndexRoute: MigrateIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
