// Custom service worker with aggressive cache clearing
// This runs before the Workbox precaching to ensure old caches are cleared

import { clientsClaim, skipWaiting } from "workbox-core";
import {
  cleanupOutdatedCaches,
  precacheAndRoute,
  type PrecacheEntry,
} from "workbox-precaching";

declare global {
  // Workbox injectManifest replaces this at build time.
  var __WB_MANIFEST: Array<string | PrecacheEntry>;
}

type ServiceWorkerRuntime = {
  addEventListener: {
    (
      type: "activate",
      listener: (event: { waitUntil: (promise: Promise<unknown>) => void }) => void,
    ): void;
    (
      type: "message",
      listener: (event: { data?: { type?: string } }) => void,
    ): void;
  };
  clients: {
    matchAll: () => Promise<Array<{ postMessage: (message: { type: string }) => void }>>;
  };
  skipWaiting: () => void;
};

// Immediately take control and skip waiting
skipWaiting();
clientsClaim();

// Clean up any outdated caches from previous builds
cleanupOutdatedCaches();

// Precache all assets generated by the build
// This will be replaced by the actual manifest at build time
const sw = globalThis as unknown as ServiceWorkerRuntime;
const injectedManifest = globalThis.__WB_MANIFEST;
precacheAndRoute(injectedManifest);

sw.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            if (!cacheName.includes("workbox-precache")) {
              return caches.delete(cacheName);
            }
          }),
        );
      })
      .then(() => {
        return sw.clients.matchAll().then((clients) => {
          for (const client of clients) {
            client.postMessage({ type: "SW_ACTIVATED" });
          }
        });
      }),
  );
});

// Handle messages from the main thread
sw.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    sw.skipWaiting();
  }
});
