// Custom service worker with aggressive cache clearing
// This runs before the Workbox precaching to ensure old caches are cleared

import {
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
  precacheAndRoute,
  type PrecacheEntry,
} from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";

declare global {
  // Workbox injectManifest replaces this at build time.
  // eslint-disable-next-line @typescript-eslint/naming-convention
  var __WB_MANIFEST: Array<string | PrecacheEntry>;
}

interface ServiceWorkerRuntime {
  addEventListener: {
    (
      type: "activate",
      listener: (event: { waitUntil: (promise: Promise<unknown>) => void }) => void,
    ): void;
    (
      type: "message",
      listener: (event: { data?: { type?: string } }) => void,
    ): void;
    (
      type: "fetch",
      listener: (event: {
        request: Request;
        respondWith: (response: Promise<Response> | Response) => void;
      }) => void,
    ): void;
  };
  clients: {
    matchAll: () => Promise<Array<{ postMessage: (message: { type: string }) => void }>>;
  };
  skipWaiting: () => void;
}

// Deliberately no skipWaiting()/clientsClaim() at module scope.
//
// Taking over immediately means a new worker claims pages that are already
// running the previous build. Those pages still hold the old module graph, so
// the next lazy route import asks for a chunk hash this worker has just purged
// from the precache - and the deploy removed it from the server too, so it
// 404s and the dynamic import throws. Letting the worker wait until every page
// using the old build has gone keeps each session on a consistent set of
// assets. The message handler below still allows an explicit, opt-in takeover.
//
// cleanupOutdatedCaches() runs at activation, which is now also the point at
// which no client depends on those assets any more.
cleanupOutdatedCaches();

// Precache all assets generated by the build
// This will be replaced by the actual manifest at build time
const sw = globalThis as unknown as ServiceWorkerRuntime;
const injectedManifest = globalThis.__WB_MANIFEST;
precacheAndRoute(injectedManifest);

// Serve the cached shell for any navigation the precache does not match.
//
// `_redirects` gives the SPA fallback (`/* /index.html 200`), but that is the
// host's job and the host needs the network. Offline, `precacheAndRoute` only
// matched precached URLs — `/` resolved via Workbox's `directoryIndex`, so a
// cold launch at `start_url` worked and a refresh on /home or /goals did not.
// The API routes are excluded: those should fail as requests rather than be
// answered with an HTML document.
registerRoute(
  new NavigationRoute(createHandlerBoundToURL("index.html"), {
    denylist: [/^\/api\//],
  }),
);

sw.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            if (!cacheName.includes("workbox-precache")) {
              return caches.delete(cacheName);
            }
          }),
        );
      })
      .then(() => {
        return sw.clients.matchAll().then((clients) => {
          for (const client of clients) {
            client.postMessage({ type: "SW_ACTIVATED" });
          }
        });
      }),
  );
});

// SPA navigations: precacheAndRoute only matches precached URLs, so offline a
// refresh worked at / and nowhere else - /home, /goals and every article
// 404'd. The _redirects SPA fallback lives on the server and needs the
// network, which is exactly what is missing. Serve the precached shell for any
// navigation instead, and let the router take it from there.
sw.addEventListener("fetch", (event) => {
  if (event.request.mode !== "navigate") return;
});

// Handle messages from the main thread
sw.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    sw.skipWaiting();
  }
});
