// Custom service worker with aggressive cache clearing
// This runs before the Workbox precaching to ensure old caches are cleared

import {
  cleanupOutdatedCaches,
  createHandlerBoundToURL,
  precacheAndRoute,
  type PrecacheEntry,
} from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";

declare global {
  // Workbox injectManifest replaces this at build time.
  // eslint-disable-next-line @typescript-eslint/naming-convention
  var __WB_MANIFEST: Array<string | PrecacheEntry>;
}

interface ServiceWorkerRuntime {
  addEventListener: {
    (
      type: "activate",
      listener: (event: { waitUntil: (promise: Promise<unknown>) => void }) => void,
    ): void;
    (
      type: "message",
      listener: (event: { data?: { type?: string } }) => void,
    ): void;
  };
  clients: {
    matchAll: () => Promise<Array<{ postMessage: (message: { type: string }) => void }>>;
  };
  skipWaiting: () => void;
}

// Deliberately no skipWaiting()/clientsClaim() at module scope.
//
// Taking over immediately means a new worker claims pages that are already
// running the previous build. Those pages still hold the old module graph, so
// the next lazy route import asks for a chunk hash this worker has just purged
// from the precache - and the deploy removed it from the server too, so it
// 404s and the dynamic import throws. Letting the worker wait until every page
// using the old build has gone keeps each session on a consistent set of
// assets. The message handler below still allows an explicit, opt-in takeover.
//
// cleanupOutdatedCaches() runs at activation, which is now also the point at
// which no client depends on those assets any more.
cleanupOutdatedCaches();

// Precache all assets generated by the build
// This will be replaced by the actual manifest at build time
const sw = globalThis as unknown as ServiceWorkerRuntime;
const injectedManifest = globalThis.__WB_MANIFEST;
precacheAndRoute(injectedManifest);

// The precached shell answers a navigation only when the network does not.
//
// `_redirects` gives the SPA fallback (`/* /index.html 200`), but that is the
// host's job and the host needs the network. Offline, `precacheAndRoute` only
// matched precached URLs — `/` resolved via Workbox's `directoryIndex`, so a
// cold launch at `start_url` worked and a refresh on /home or /goals did not.
// The API routes are excluded: those should fail as requests rather than be
// answered with an HTML document.
//
// Network first, though, because Permissions-Policy and CSP travel on the
// document response: answering a navigation from the precache pins both to
// whatever the server sent when the shell was captured. That is how
// `camera=()` outlived the deploy that changed it to `camera=(self)` — an
// installed app went on serving its captured shell, so getUserMedia stayed
// blocked by policy and the scanner reported the camera as denied, with no
// site setting able to grant it back. A header-only deploy has to be able to
// reach an installed app; nginx already marks /index.html `no-store` on the
// same reasoning.
const precachedShell = createHandlerBoundToURL("index.html");

// Without a bound, a cold launch on a bad connection waits on the document for
// as long as the network takes to give up. The shell is already on disk.
const SHELL_NETWORK_TIMEOUT_MS = 3000;

registerRoute(
  new NavigationRoute(
    async (options) => {
      try {
        const response = await Promise.race([
          fetch(options.request),
          new Promise<never>((_, reject) => {
            setTimeout(() => reject(new Error("shell network timeout")), SHELL_NETWORK_TIMEOUT_MS);
          }),
        ]);

        // A 5xx or a captive-portal redirect is not a shell. Prefer the real one.
        if (response.ok) return response;
      } catch {
        // Offline, or slower than it is worth waiting for.
      }

      return precachedShell(options);
    },
    { denylist: [/^\/api\//] },
  ),
);

sw.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) => {
        return Promise.all(
          cacheNames.map((cacheName) => {
            if (!cacheName.includes("workbox-precache")) {
              return caches.delete(cacheName);
            }
          }),
        );
      })
      .then(() => {
        return sw.clients.matchAll().then((clients) => {
          for (const client of clients) {
            client.postMessage({ type: "SW_ACTIVATED" });
          }
        });
      }),
  );
});


// Handle messages from the main thread
sw.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") {
    sw.skipWaiting();
  }
});
