// Material 3 Expressive Color System Theme Mapping
// Semantic roles mapped to CSS variables from variables.css

export const lightTheme = {
  primary: "var(--primary-40)",
  onPrimary: "var(--primary-100)",
  primaryContainer: "var(--primary-90)",
  onPrimaryContainer: "var(--primary-10)",
  secondary: "var(--secondary-40)",
  onSecondary: "var(--secondary-100)",
  secondaryContainer: "var(--secondary-90)",
  onSecondaryContainer: "var(--secondary-10)",
  tertiary: "var(--tertiary-40)",
  onTertiary: "var(--tertiary-100)",
  tertiaryContainer: "var(--tertiary-90)",
  onTertiaryContainer: "var(--tertiary-10)",
  error: "var(--error-40)",
  onError: "var(--error-100)",
  errorContainer: "var(--error-90)",
  onErrorContainer: "var(--error-10)",
  surface: "var(--neutral-99)",
  onSurface: "var(--neutral-10)",
  surfaceVariant: "var(--neutral-variant-90)",
  onSurfaceVariant: "var(--neutral-variant-30)",
  outline: "var(--neutral-variant-50)",
  outlineVariant: "var(--neutral-variant-80)",
  background: "var(--neutral-99)",
  onBackground: "var(--neutral-10)",
  surfaceContainerLowest: "var(--neutral-100)",
  surfaceContainerLow: "var(--neutral-95)",
  surfaceContainer: "var(--neutral-90)",
  surfaceContainerHigh: "var(--neutral-80)",
  surfaceContainerHighest: "var(--neutral-variant-90)",
};

export const darkTheme = {
  primary: "var(--primary-80)",
  onPrimary: "var(--primary-20)",
  primaryContainer: "var(--primary-30)",
  onPrimaryContainer: "var(--primary-90)",
  secondary: "var(--secondary-80)",
  onSecondary: "var(--secondary-20)",
  secondaryContainer: "var(--secondary-30)",
  onSecondaryContainer: "var(--secondary-90)",
  tertiary: "var(--tertiary-80)",
  onTertiary: "var(--tertiary-20)",
  tertiaryContainer: "var(--tertiary-30)",
  onTertiaryContainer: "var(--tertiary-90)",
  error: "var(--error-80)",
  onError: "var(--error-20)",
  errorContainer: "var(--error-30)",
  onErrorContainer: "var(--error-90)",
  surface: "var(--neutral-10)",
  onSurface: "var(--neutral-90)",
  surfaceVariant: "var(--neutral-variant-30)",
  onSurfaceVariant: "var(--neutral-variant-80)",
  outline: "var(--neutral-variant-60)",
  outlineVariant: "var(--neutral-variant-30)",
  background: "var(--neutral-10)",
  onBackground: "var(--neutral-90)",
  surfaceContainerLowest: "var(--neutral-variant-30)",
  surfaceContainerLow: "var(--neutral-variant-10)",
  surfaceContainer: "var(--neutral-20)",
  surfaceContainerHigh: "var(--neutral-30)",
  surfaceContainerHighest: "var(--neutral-40)",
};